# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "efa73bd498c8913a105622a83e10b460"
name = "prodaidesigner"
handle = "prodaidesigner"
application_url = "https://celebrities-instructors-trick-chargers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lushvista.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://celebrities-instructors-trick-chargers.trycloudflare.com/auth/callback",
  "https://celebrities-instructors-trick-chargers.trycloudflare.com/auth/shopify/callback",
  "https://celebrities-instructors-trick-chargers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
